general:
  device: "auto"

data_collator:
  padding: "longest"
  max_length: null
  padding_side: "right"
  truncation_side: "right"
  text_colname: "text"
  label_colname: "NER"

model:
  embedding_dim: 300
  hidden_dim: 512
  nonlinearity: "tanh"
  bias: True

optimizer:
  lr: 1.0e-3
  betas: [ 0.9, 0.999 ]
  weight_decay: 0.01

trainer:
  grad_clip_max_norm: 1
  use_class_weights: True
  class_weights: null

train_and_eval:
  checkpoint_every: 1
  num_workers: 0
